### ISSUE TITLE
Vue-cli-service dirname error on windows

### ISSUE THREAD

**Issue by Tjark-Kuehl** [universal-vue/uvue#11]
**Describe the bug**
After you pushed the update alpha.6 my friend had an error after his server restarts with nodemon.
The error is called
`..\node_modules\.bin\vue-cli-service:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^`

SyntaxError: missing ) after argument list
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
× error Server crashed`
It leads to the file `\node_modules\.bin\vue-cli-service` where the line `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")` is located.

_To be clear this error only exists on windows. Linux works like a charm_

**To Reproduce**
Go to /api in the browser and see a basic api output.
Now go to src/api/routes/index.js and change the body message.

[**Repository**](https://github.com/Tjark-Kuehl/uvue-reproduction)

**Expected behavior**
The server restarts without an error message

**Additional context**

Please indicate versions of:
```
node: 11.x
vue-cli: Newest
uvue: Newest
os: Windows 10
browser: Google Chrome 71
```

**Comment by chymz** [comment]
Thanks for the PR, I will publish this tomorrow !

**Comment by chymz** [comment]
Can you try `0.1.0-alpha.7`

**Comment by Tjark-Kuehl** [comment]
Works like a charm
