### ISSUE TITLE
_vm._ssrEscape is not a function

### ISSUE THREAD

**Issue by camwhite** [universal-vue/uvue#43]
After a watch reloads the server and sometimes after a build this error is thrown..

```
Error: _vm._ssrEscape is not a function
    at vue__WEBPACK_IMPORTED_MODULE_4__.default.config.errorHandler (webpack-internal:///./node_modules/@uvue/core/lib/initApp.js:85:91)
    at globalHandleError (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1869:34)
    at handleError (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1838:5)
    at VueComponent.Vue._render (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3544:7)
    at VueComponent.updateComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4060:21)
    at Watcher.get (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4473:25)
    at new Watcher (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4462:12)
    at mountComponent (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:4067:3)
    at VueComponent.Vue.$mount (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:8405:10)
    at init (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:3115:13)
```

The only thing that corrects it is `rm -rf node_modules/.cache`, sorry I can't really provide more.

```
node: 12.3.1
vue-cli: 4.0.5
uvue: 0.1.1
os: ubuntu
browser: chrome
```

**Comment by chymz** [comment]
I think I've found an issue with webpack configuration, can you list directories you can see in this `.cache` folder ?

**Comment by mr-luke** [comment]
Similar issue. Sometimes is end up with `_ssrNode is not a function`, next time with `_ssrAttr`. When I remove `.cache` content, it runs correctly.

**Comment by chymz** [comment]
Can you try with `0.1.5` ?

**Comment by chymz** [comment]
No activity, closing

**Comment by robodude666** [comment]
Can confirm upgrading from 0.1.1 to 0.1.3+ fixes the issue.
