### ISSUE TITLE
Cannot install UVue over vue enterprise boilerplate

### ISSUE THREAD

**Issue by sovofeel** [universal-vue/uvue#7]
**Describe the bug**
I got an error after i installed the UVue over [vue enterprise boilerplate](https://github.com/chrisvfritz/vue-enterprise-boilerplate) 

```bash
 ERROR  TypeError: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Object.is (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/elements/NewElement.js:15:52)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:54:14)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at Object.findNodes [as default] (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at AstElement.find (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/elements/AstElement.js:21:44)
    at AstElement.findOne (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/elements/AstElement.js:26:21)
    at CodeFixer.fixPlugin (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/vue-cli-plugin-ssr/uvue/CodeFixer.js:258:27)
    at CodeFixer.fixVuex (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/vue-cli-plugin-ssr/uvue/CodeFixer.js:216:17)
```
**To Reproduce**
check [**reproduction repo**](https://github.com/sovofeel/boilerplate_uvue_example)

in my `src/main.js` i've got store and router from the context
```javascript
export default ({ router, store }) => {
  const app = new Vue({
    router,
    store,
    i18n: i18n(),
    render: h => h(App)
  })
```
**Expected behavior**
Everything works fine when  I use *VueNeue* just set options in `vueneue.config.js` 
```javascript
module.exports = {
  templatePath: 'src/index.html', // HTML Template to render pages (relative to your project path)
  paths: {
    main: './src/main', // File where you do a new Vue
    router: './src/router/', // File where you do a new Router
    store: './src/state/store' // File where you do a new Vuex.Store
  },
}
```

**Additional context**

Please indicate versions of:
```
node: 11.2.0
vue-cli: 3.1.5
uvue: 0.1.0-aplha
os: MacOS High Sierra
browser: N/A
```

**Comment by chymz** [comment]
Well, it's a complex case.

Can you try to change code in `src/state/store.js` before installing UVue plugin:

```js
import Vue from 'vue'
import Vuex from 'vuex'

import modules from './modules'

Vue.use(Vuex)

export default () => {
  const store = new Vuex.Store({
    modules,
    // Enable strict mode in development to get a warning
    // when mutating state outside of a mutation.
    // https://vuex.vuejs.org/guide/strict.html
    strict: process.env.NODE_ENV !== 'production',
  })

  // Automatically run the `init` action for every module,
  // if one exists.
  for (const moduleName of Object.keys(modules)) {
    if (modules[moduleName].actions && modules[moduleName].actions.init) {
      store.dispatch(`${moduleName}/init`)
    }
  }

  return store
}
```

**Comment by sovofeel** [comment]
got new error

```bash
? Install UVue plugins? Async Data method, Vuex, Middlewares system, Error handler
? Enable Vuex behaviors Use onHttpRequest() Vuex actions
? Install server plugins? Cookie parser, Static files serving, GZIP compression, Modern build
? Define a secret for your cookies yay
? Do you want to use Docker to deploy your app? No

🚀  Invoking generator for @uvue/vue-cli-plugin-ssr...
📦  Installing additional dependencies...

added 51 packages from 67 contributors and audited 71700 packages in 43.386s
found 6 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
⠋  Running completion hooks...● start Searching Router file...
✖ error No Router file detected!
● start Searching Vuex file...
⠙  Running completion hooks... ERROR  TypeError: Cannot read property 'type' of null
TypeError: Cannot read property 'type' of null
    at Object.is (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/elements/NewElement.js:15:52)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:54:14)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at findNodes (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at Object.findNodes [as default] (/Users/username/Desktop/vue-enterprise-boilerplate/node_modules/@uvue/rquery/lib/utils/findNodes.js:69:17)
    at AstElement.find (/Users/ar
```

i'll wrap my src/route/index.js in func
```javascript
import Vue from 'vue'
import VueRouter from 'vue-router'
// https://github.com/declandewet/vue-meta
import VueMeta from 'vue-meta'
// Adds a loading bar at the top during page loads.
import NProgress from 'nprogress/nprogress'
import store from '@state/store'
import routes from './routes'

Vue.use(VueRouter)
Vue.use(VueMeta, {
  // The component option name that vue-meta looks for meta info on.
  keyName: 'page',
})

export default () => {
  const router = new VueRouter({
    routes,
    // Use the HTML5 history API (i.e. normal-looking routes)
    // instead of routes with hashes (e.g. example.com/#/about).
    // This may require some server configuration in production:
    // https://router.vuejs.org/en/essentials/history-mode.html#example-server-configurations
    mode: 'history',
   
  return router
}
```

and my `src/state/store.js`

```javascript
import Vue from 'vue'
import Vuex from 'vuex'

import modules from './modules'

Vue.use(Vuex)

export default () => {
  const store = new Vuex.Store({
    modules,
    // Enable strict mode in development to get a warning
    // when mutating state outside of a mutation.
    // https://vuex.vuejs.org/guide/strict.html
    strict: process.env.NODE_ENV !== 'production',
  })

  // Automatically run the `init` action for every module,
  // if one exists.
  for (const moduleName of Object.keys(modules)) {
    if (modules[moduleName].actions && modules[moduleName].actions.init) {
      store.dispatch(`${moduleName}/init`)
    }
  }
  return store
}

```

my `src/main.js`

```javascript
import Vue from 'vue'
import App from './app'
import createRouter from '@router'
import createStore from '@state/store'
import '@components/_globals'

// Don't warn about using the dev version of Vue in development.
Vue.config.productionTip = process.env.NODE_ENV === 'production'

// If running inside Cypress...
if (window.Cypress) {
  // Ensure tests fail when Vue emits an error.
  Vue.config.errorHandler = window.Cypress.cy.onUncaughtException
}

const router = createRouter()
const store = createStore()

const app = new Vue({
  router,
  store,
  render: h => h(App),
}).$mount('#app')

// If running inside Cypress...
if (window.Cypress) {
  // Attach the app to the window, which can be useful
  // for manually setting state in Cypress commands
  // such as `cy.logIn()`.
  window.__app__ = app
}
```

**Comment by sovofeel** [comment]
Working example [boilerplate and vueneue](https://github.com/sovofeel/vueneue-boilerplate)

**Comment by sovofeel** [comment]
Well, i fix [https://github.com/sovofeel/uvue-boilerplate](uvue-boilerplate) and now it's work

**Comment by chymz** [comment]
Thanks for reporting and sharing solution !
